[package]
name = "color-cycle"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
ctrlc = "3.4.5"
libc = "0.2.169"
serde = "1.0.217"
serde_json = "1.0.134"
term_size = "0.3.2"
